S_MULTIPLE_CHOICE = "multiple choice"
S_NUMBER_OF_QUESTIONS = "number of questions"
S_NUMBER_OF_ATTEMPTS = "number of attempts"
S_MULTIPLE_CHOICE_USE_INDEX = "multi-choice: select using index"
S_QUESTION_FILE_PATH = "question file path"
S_SCORE_FILE_PATH = "score file path"

Q_QUESTIONS = "questions"
Q_QUESTION = "question"
Q_ANSWER = "answer"
Q_ANSWER_OPTIONS = "multi-choice options"
